---
title: "Assignment 8"
author: "Penelope Weekes"
date: "2023-01-26"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

# Code Reflection
#### 1. Go through your recent assignments and the posted solutions ([Assignment 6 posted solutions](https://lvash.github.io/BIOL1007A/Assignment-6-dplyr_solutions.html) and [Weekly Assignment 2 solutions](https://lvash.github.io/BIOL1007A/Solutions_Weekly-Assignment-2.html)) - compare your code to the posted code.
  - Can you run your simulated data function with new values for the means? If not, what do you need to change about your code?
  - Are there differences between the posted code and yours? Did you notice you were missing anything?
  - Make sure you annotate your code using `#` and leave brief descriptions of your thought process.

I copied my original submissions for [Assignment 6](assignment6.html) and [Weekly Assignment 2](week2.html) (linked here) and created new R Markdowns with the answers to the questions (linked below):

  - [Assignment 6 Annotated](assignment6annotated.html)   
  - [Weekly Assignment 2 Annotated](weeklyassignment2annotated.html)

# Code annotation

#### 2. I used `dryad` data to reconstruct a publication-quality figure. Copy my code into an Rmd file and annotate what each `ggplot` line of code is doing, including any arguments. You can use a combination of googling and ‘trial/error coding:’ change the arguments/options to visually see how it affects the plot.

```{r}
## Set up libraries
library(tidyverse)
library(ggthemes)


# Data obtained from Veysey Powell and Babbitt 2016: An experimental test of buffer utility as a technique for managing pool-breeding amphibians https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.547rp

dryadData <- read.table("Data/veysey-babbitt_data_amphibians.csv", header=TRUE, sep=",", stringsAsFactors = TRUE)

# glimpse(dryadData)
# head(dryadData)
# table(dryadData$species)

dryadData$species<-factor(dryadData$species, labels=c("Spotted Salamander", "Wood Frog")) #creating 'labels' to use for the plot

#class(dryadData$treatment)
dryadData$treatment <- factor(dryadData$treatment, 
            levels=c("Reference",
                     "100m", "30m")) ## gives 'labels' for x-axis


p<- ggplot(data=dryadData, ## calls data for graph
       aes(x=interaction(wetland, treatment), ## groups treatment and wetland
           y=count.total.adults, fill=factor(year))) + ## groups y-axis sub graphs(?) by year
  geom_bar(position="dodge", stat="identity", color="black") + ## indicates bar graph, position, and color
  ylab("Number of breeding adults") + ## y-axis title
  xlab("") + ## no x-axis title
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) + ## shows y-axis should be broken up by 100s
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) + ## gives x-axis tick mark labels
  facet_wrap(~species, nrow=2, strip.position="right") + ## makes it two graphs (separated by species) instead of one
  theme_few() + scale_fill_grey() + ## changed to greyscale 
  theme(panel.background = element_rect(fill = 'gray94', color = 'black'), ## colors panel backgrounds and borders them black
        legend.position="top", ## moves legend to top
        legend.title= element_blank(), ## specifies no legend title
        axis.title.y = element_text(size=12, face="bold", colour = "black"), ## makes "number of breeding adults" bolder and larger
        strip.text.y = element_text(size = 10, face="bold", colour = "black")) + ## formats "spotted salamander" and "wood frog"
  guides(fill=guide_legend(nrow=1,byrow=TRUE)) ## makes legend one row (instead of two)

p

```



